// Tabler icons baked into assets/icons/tabler.svg by `npm run icons`.
// Values are Tabler icon names — the same names icon.html callers pass,
// so `npm run icons` and the templates can be diffed against each other.
export default [
  "search",
  "sun",
  "moon",
  "menu-2",
  "globe",
  "x",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "chevron-down",
  "note",
  "info-circle",
  "bulb",
  "alert-triangle",
  "alert-octagon",
  "copy",
  "copy-check",
  "external-link",
  "brand-github",
  "brand-x",
  "brand-mastodon",
  "brand-bluesky",
  "rss",
  "mail",
  "brand-linkedin",
  "link",
];
